---
satellite_organization: "CRAZY.LAB"
satellite_initial_location: "loc-local"


satellite_products:
  - name: Red Hat Enterprise Linux for x86_64
    repository_sets:
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS (Kickstart)
        releasever: 9.6
        download_policy: "immediate"
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
        releasever: 9
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream (Kickstart)
        releasever: 9.6
        download_policy: "immediate"
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
        releasever: 9
      - name: Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)
  - name: Red Hat Enterprise Linux for x86_64 - Extended Update Support
    repository_sets:
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS - Extended Update Support (RPMs)
        releasever: 9.6
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream - Extended Update Support (RPMs)
        releasever: 9.6


# https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/role/content_view_publish/
# https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/role/content_view_publish/
satellite_content_views:
  - name: CV-RHEL-9
    repositories:
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9
        product: 'Red Hat Enterprise Linux for x86_64'
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9
        product: 'Red Hat Enterprise Linux for x86_64'
      - name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.6
        product: 'Red Hat Enterprise Linux for x86_64'
      - name: Red Hat Enterprise Linux 9 for x86_64 - AppStream Kickstart 9.6
        product: 'Red Hat Enterprise Linux for x86_64'

  - name: CCV-RHEL-9
    components:
      - content_view: "CV-RHEL-9"
        latest: true

satellite_activation_keys:
  - name: "AK-RHEL-9-DEV"
    auto_attach: false
    lifecycle_environment: Development
    content_view: CCV-RHEL-9

satellite_lifecycle_environments:
  - name: "Development"
    label: DEV
    prior: "Library"
  - name: "Production"
    label: PROD
    prior: "Development"


# https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/role/hostgroups/
satellite_hostgroups:
  - name: "HG_DEFAULT_RHEL_9_DEV"
    lifecycle_environment: "Development"
    content_view: "CCV-RHEL-9"
    content_source: "lab-satellite-6.crazy.lab"
    environment: ""
    domain: "crazy.lab"
    architecture: x86_64
    operatingsystem: "RedHat 9.6"
    kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.6"
    ptable: "Kickstart default"
    pxe_loader: "Grub2 UEFI"
    locations:
      - "loc-local"
    organization: "CRAZY.LAB"
    activation_keys: "AK-RHEL-9-DEV"

satellite_settings:
  - name: destroy_vm_on_host_delete
    value: true
