---
satellite_rhsm_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38303664306631306465366137306237663862656365656530613737386133616530333033356537
          3037313834653561383234323539393736323062633165610a613462353631366535656363623963
          32363265646330623834336432326133356530343162653061353764616362373138616231323964
          3430623435303332660a633134383265353066326463386639306235336236656631646434653866
          66333235336130383365623939383235346239376162633038373138386436666334
satellite_rhsm_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64313765616564393932393233616435376533323432343563376164323966326163333835623065
          3063633137316532633232313035373439613236633566640a323033376335343435623631383736
          35343963373964363934323266633435313833656262663066643865343530653564393233323662
          3263393930653538650a363863623366376337363639366433623066646565656239393363316565
          6265
# Check https://access.redhat.com/articles/3626371
REDHAT_API_OFFLINE_TOKEN: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37613437363333316138633334373535333061643039396231346565323832313161356432366630
          3331393331633263646236663631316432303735356365330a383233613832316639636632333362
          31323932373034613730386439613764643836626632393737623039633330373161363461343239
          3433393134303138330a323630323936336138643431616133666339326135326466656537663135
          36373065313538366265336464636433303065396661613561316435386661313866323165643163
          36383630653833663161363661313263366438373530313262396532343437613031373965303564
          38373137626263626534306433353162363036383961393034333932636136326362613831346363
          63336562376232636466663663333936353434633638656262323435383230393630323638346564
          63666532353663306265396364346237353861383837613163353534316331323163303330323363
          37346534316438336262613433366134323864386439353161646262396230633236336230626564
          62396637326533616338316539613364326465316338363166633030393934653836623538623432
          39333662376165306235656364623166663165633139646464663532643964623238633133373333
          39373136336232643166656230313139653632393762316266393333613430626165653336313536
          37643837643366666465666238346165643730333437633762356134373861353435663562656631
          34353230366232636263383237653266336338353838653065393965353861316538346263613231
          30653034393135373931613435303638666630333163333237303965653061323164663263376262
          62643731663361373733383333633762383334356165373566356333366262633235396464346336
          38653261303130636537613762333630313939343561666235373038366239396236653961363539
          31356566666166386130363233626338373232323338636561313464643930613765346335666163
          34373337333132666630646366336464356337376631343038303933643834306330303435303836
          39366231643136343836393034366537336164396665373932353235366266303464366662623038
          35316635663439363736656133396534666234626663303739653765646138353163366430626464
          39366366656139666234643062623834363531363531623462663564303461303263326564643964
          34333365613066303338623263663665373465346162623461656463643034333237366231616637
          65353961326235393939343964643166616133363633373262396233306539623836623863653334
          32383539643964363736303261656162326431383336646135396638326134383462636231393764
          62353931333566613831633532653535353635376331623135383362633862316562626463653735
          36316330306361343565303630336462333230643630666232646133613862316461613233373434
          32323764636666613036653466363638306237366331323463613361363266643364393164623766
          32323339636233623330373561336236303066663162323530663036343939383339616435663464
          36386566386632373136393862376535333764396637366334306665626463326262616331393930
          37373465376634373362623662303738356631313731303330363364306439333734613235326362
          64316363363130613538623035393437353035653436393931383062373436646636643035646434
          36616238613636646332386634373264646533626436316536653063643637306338333235636332
          64653032366665393761326562326661633939363166356563666266323462656437393965333436
          33643233393535326631313862363861333636646231323364646434653661356330656530383239
          36643334393566663335366337626366386439303335323731303332376361643538323132356135
          33346530616538383161663464376139646365393034336138653163633433333432636436656435
          64393938333037323262646265313033643236396535303666336238663635643765386336376265
          61313936356162383166383261663236373066356361316132643935343432376236346437366537
          3362

satellite_server_url: "https://{{ inventory_hostname }}"
sat_initial_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61316435396535366464373763643134393965653261613636643439613166626463633566333935
          6535326635613637623136653134346361636661373434630a303563343539376631656239393738
          30626530633331653061646431383734633666666632323330656563643362353664386139323637
          3338633534613665300a393330363039306166336363613263326666353061366362653030333937
          3164

# Password of the initial user
sat_initial_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61323830623936616439366137633336643565303731363964613964653639616435373239633638
          6333646536636433636139623836643836313232313064360a333935383635646533333235633566
          62313535373564646537323731386230663061666665346132346233336338666137653738633865
          6231333138636138390a653537343738373162613734663665313537396231326636373532643738
          34383562306437653866663435373136653139643530646330653363316335633463

# Grab appropriate UUID from Subscription Allocation page in Red Hat Customer Portal
# https://access.redhat.com/management/subscription_allocations
satellite_manifest_uuid: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33616538313935353331643430646130336537663563623661336164396631373263313932373263
          3739313263326130653637373935353963353637333762310a336236633662376238333130303236
          35393061343433613831336161646234646165303530626564623131643737383865366135613834
          3766396136346662380a366436636437613135633532373065313535316561613866393961663165
          32373263393432303666353737343232653731323864646366613332393361646265333862343031
          3033333165373337376337326238613530376339376335353635

satellite_compute_ressource_rhv_username: admin@internal
satellite_compute_ressource_rhv_password: supersecret

# Check https://access.redhat.com/management/activation_keys
satellite_rhsm_organization_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33613137353564313931323663353832383963376632383762646631333661663339633564303133
          3430316561383536366137363234643432353831653832300a333764626138643930633362333563
          35343361666431323439303337306666653761666563613031653362396137306562313634666231
          6662316138316366630a646230343162663338663166373538333438333664623562373130316664
          3733
satellite_rhsm_activationkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35663736313033653638396162623033393037633164393930393437326332323639613435366132
          3135316562623631666639653562343962396161343733340a633166383032643962636336303365
          37633535653164346166333435666366306132306336656361396564316164643837646637353335
          6465336430303930340a386263386438626638373661363134623436636336313866303830623435
          66376639316532316539343533343738616537643636626339656165376537373066

# SSH keys for Satellite Remote Execution
sat_remote_execution_ssh_private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63636232343034636432656432336662613835376136623433383435356135316439623937343639
          6632316233373865353062623565353933303137336265380a366563343638353262323739613763
          36633937343564356365663865343633636261643233663137303637613034626266306534386561
          3161316435353031310a666631303235376437616361356366336537306530643037613439643536
          66363763646361306435376438646564316435626264303861396364633961396665623039393531
          35323834343766333131363334663261656562353365386131383431626266393032336163666639
          36313732643831623430313565323862343261663864643964666266613336333231396466633765
          66396332656230346266666332633033613764373964343761356537356630386630333362363632
          66336266303030393939376633323665383961646666313163353435363565346232616338383437
          61383761313834313936333339666534373930383839646431386636346462323538326235616363
          32643361376536336333313933393661323133393534666362333364363737386363316662613564
          61383134613963303262653033623037653435373033356630636361306165633237356635646166
          32366365313966336237333061313366343433313066626634613665326133316563336535343133
          36633265356362356338386564613465623633656165393766653464303139303262333936326133
          35616535316131363361653730656464333138316332333634646234383435613436376262303630
          36643632363933616234316162353762346136373336366439303239613963643334383539643039
          30363762333830646338623462663439333531333039653065346531656630623366316362643766
          65663762376365386533616334323839323364633264636338356163333837323163303736313139
          65633362653830386562393039633239653764386630613366323630366638316263613866373061
          32306638633132323562366534613937613636633733653562633437663562663362633139643761
          65646662636630313562636433653937376333613062653734346662396235666339363363626638
          39393030333334366563613539353032393530346332356664666238633532356138353331613630
          65303666643735333736383534373963646232366561313835323166313464386466366536636662
          66346438323163366432393861666233663464333439396531363766653033653463313965613662
          33633935633437636535346365306638656235343264323136653030633736336138

sat_remote_execution_ssh_public_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36343061373363613162666436353563393633353231646533636638666135383865656631386335
          3736396339653135323833343865623865396434353663330a386662643034646638393835383534
          36323537373163333165353763396630386239613034666365643437336163323765373532653561
          3462323464653736310a333432373566366561313662323636383166643734353363663963653436
          35623363343237633930356137313836313266386237363339343637303431633365616263613533
          32633163363332333635356536653230653863633566383638356234346338363434383861613963
          35356432626665366364343834356636333233323066663132653734326334643039396665353630
          34313334393963396335663532326138383836353964663033633038396435383662643061323766
          34656530386432643935346631363835383835313936656439666563323765396636

# Below credentials are used to connect to Satellite after the installation. Change it,
# if you want to use a different user than the initially created one
satellite_username: '{{ sat_initial_user }}'
satellite_password: '{{ sat_initial_password }}'
...
