---
# These are the variables that are used by the role redhat.rhel_system_roles.rhc
rhc_state: 'present'
rhc_auth:
  activation_keys:
    keys: ['{{ satellite_rhsm_activationkey }}']
  rhc_organization: '{{ satellite_rhsm_organization_id }}'

# Repositories to enable on the Satellite server (the Linux host, not the application)
rhc_repositories:
  - name: 'rhel-9-for-x86_64-baseos-rpms'
    state: 'enabled'

  - name: 'rhel-9-for-x86_64-appstream-rpms'
    state: 'enabled'

  - name: 'satellite-6.18-for-rhel-9-x86_64-rpms'
    state: 'enabled'

  - name: 'satellite-maintenance-6.18-for-rhel-9-x86_64-rpms'
    state: 'enabled'

# RHEL release to set in subscription-manager
rhc_release: 9

# We don't want to register to Red Hat Insights
rhc_insights:
  state: 'absent'
  autoupdate: false
  remediation: 'absent'

# if you need a proxy, use the following variables
# rhc_proxy:
#   hostname: 'proxy-hostname'
#   port: 4321
#   username: 'proxy-hostname'
#   password: 'proxy-password'