---
# Firewalld rules for Satellite Server
# Managed by redhat.rhel_system_roles.firewall
firewall:
  - port:
      - '8000/tcp'
      - '9090/tcp'
    service:
      - 'tftp'
      - 'http'
      - 'https'
    zone: 'public'
    state: 'enabled'
    permanent: true
    immediate: true
