---
satellite_content_credentials:
  - name: 'gpg-epel-epel-rhel-9'
    content_type: 'gpg_key'
    content: "{{ lookup('url', 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9', split_lines=false )}}"

  - name: 'gpg-epel-epel-rhel-10'
    content_type: 'gpg_key'
    content: "{{ lookup('url', 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-10', split_lines=false )}}"
