---
sat_products:
  # Red Hat repositories
  #
  - name: 'Red Hat Enterprise Linux for x86_64'
    repository_sets:
      - name: 'Red Hat Enterprise Linux 10 for x86_64 - BaseOS (RPMs)'
        releasever: '10'
        download_policy: 'on_demand'

      - name: 'Red Hat Enterprise Linux 10 for x86_64 - AppStream (RPMs)'
        releasever: '10'
        download_policy: 'on_demand'

      - name: 'Red Hat Enterprise Linux 10 for x86_64 - BaseOS (Kickstart)'
        releasever: '10.0'
        download_policy: 'immediate'

      - name: 'Red Hat Enterprise Linux 10 for x86_64 - AppStream (Kickstart)'
        releasever: '10.0'
        download_policy: 'immediate'

      - name: 'Red Hat Satellite Client 6 for RHEL 10 x86_64 (RPMs)'
        download_policy: 'on_demand'

      - name: 'Red Hat Enterprise Linux 10 for x86_64 - Extensions (RPMs)'
        releasever: '10'
        download_policy: 'on_demand'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)'
        releasever: '9'
        download_policy: 'on_demand'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)'
        releasever: '9'
        download_policy: 'on_demand'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS (Kickstart)'
        releasever: '9.6'
        download_policy: 'immediate'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream (Kickstart)'
        releasever: '9.6'
        download_policy: 'immediate'

      - name: 'Red Hat Satellite Client 6 for RHEL 9 x86_64 (RPMs)'
        download_policy: 'on_demand'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - Extensions (RPMs)'
        releasever: '9'
        download_policy: 'on_demand'

      - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)'
        releasever: '8'
        download_policy: 'on_demand'

      - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)'
        releasever: '8'
        download_policy: 'on_demand'

      - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS (Kickstart)'
        releasever: '8.10'
        download_policy: 'immediate'

      - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream (Kickstart)'
        releasever: '8.10'
        download_policy: 'immediate'

      - name: 'Red Hat Satellite Client 6 for RHEL 8 x86_64 (RPMs)'
        download_policy: 'on_demand'

  - name: 'Red Hat Enterprise Linux High Availability for x86_64'
    repository_sets:
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - High Availability (RPMs)'
        releasever: '9'
        download_policy: 'on_demand'

  - name: 'Red Hat Ansible Automation Platform'
    repository_sets:
      - name: 'Red Hat Ansible Automation Platform 2.5 for RHEL 8 x86_64 (RPMs)'
        download_policy: 'on_demand'

      - name: 'Red Hat Ansible Automation Platform 2.5 for RHEL 9 x86_64 (RPMs)'
        download_policy: 'on_demand'

      - name: 'Red Hat Ansible Automation Platform 2.6 for RHEL 9 x86_64 (RPMs)'
        download_policy: 'on_demand'
  
  - name: 'Red Hat Satellite Capsule'
    repository_sets:
      - name: 'Red Hat Satellite Capsule 6.18 for RHEL 9 x86_64 (RPMs)'
        download_policy: 'on_demand'