---
# custom products
#
sat_custom_products:
  - name: 'prd-epel-epel'
    repositories:
      - name: 'repo-epel-epel-9-rhel-9'
        url: 'https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/'
        gpg_key: 'gpg-epel-epel-rhel-9'
        content_type: 'yum'
        download_policy: 'on_demand'
        mirroring_policy: 'mirror_complete'
        arch: 'x86_64'
        auto_enabled: false
        ignorable_content: []
      - name: 'repo-epel-epel-10-rhel-10'
        url: 'https://dl.fedoraproject.org/pub/epel/10/Everything/x86_64/'
        gpg_key: 'gpg-epel-epel-rhel-10'
        content_type: 'yum'
        download_policy: 'on_demand'
        mirroring_policy: 'mirror_complete'
        arch: 'x86_64'
        auto_enabled: false
        ignorable_content: []
