---
# Define the Domains
satellite_domains:
  - name: 'crazy.lab'
    description: 'crazy.lab'
    locations:
      - '{{ satellite_location }}'
    organizations:
      - '{{ satellite_organization }}'

  - name: 'deploy.crazy.lab'
    description: 'deploy.crazy.lab'
    locations:
      - '{{ satellite_location }}'
    organizations:
      - '{{ satellite_organization }}'
