---
# Define the Domains
satellite_domains:
  - name: 'crazy.lab'
    description: 'crazy.lab'
    locations:
      - '{{ satellite_location }}'
    organizations:
      - '{{ satellite_organization }}'

  - name: 'customer.prod'
    description: 'customer.prod'
    locations:
      - '{{ satellite_location }}'
    organizations:
      - '{{ satellite_organization }}'

  - name: 'customer.stor'
    description: 'customer.stor'
    locations:
      - '{{ satellite_location }}'
    organizations:
      - '{{ satellite_organization }}'

  - name: 'customer.sap'
    description: 'customer.sap'
    locations:
      - '{{ satellite_location }}'
    organizations:
      - '{{ satellite_organization }}'
