---
# Define the Subnets
satellite_subnets:
  - name: 'sn-172_16_100_0'
    network: '172.16.100.0'
    mask: '255.255.255.0'
    gateway: '172.16.100.254'
    boot_mode: 'Static'
    ipam: 'None'
    tftp_proxy: '{{ inventory_hostname }}'
    template_proxy: '{{ inventory_hostname }}'
    discovery_proxy: '{{ inventory_hostname }}'
    remote_execution_proxies:
      - '{{ inventory_hostname }}'
    dns_primary: '172.16.100.254'
    # dns_secondary: '172.16.100.254'
    domains:
      - 'crazy.lab'
    organizations:
      - '{{ satellite_organization }}'
    locations:
      - '{{ satellite_location }}'

  - name: 'sn-172_16_80_0'
    network: '172.16.80.0'
    mask: '255.255.255.0'
    gateway: '172.16.80.254'
    boot_mode: 'Static'
    ipam: 'None'
    tftp_proxy: '{{ inventory_hostname }}'
    template_proxy: '{{ inventory_hostname }}'
    discovery_proxy: '{{ inventory_hostname }}'
    remote_execution_proxies:
      - '{{ inventory_hostname }}'
    dns_primary: '172.16.80.1'
    domains:
      - 'deploy.crazy.lab'
    organizations:
      - '{{ satellite_organization }}'
    locations:
      - '{{ satellite_location }}'