---
# Define Content Views that contain custom Products
sat_content_views_custom_products:
  - name: 'cv-epel-epel-rhel'
    repositories:
      - name: 'repo-epel-epel-9-rhel-9'
        product: 'prd-epel-epel'
      - name: 'repo-epel-epel-10-rhel-10'
        product: 'prd-epel-epel'

  
