---
# Define the Rolling Content Views
# auto_publish: true makes these "rolling" -- new repo content is
# automatically published without a manual publish step.
sat_rolling_content_views:
  - name: 'rcv-rhcdn-base-rhel-9'
    auto_publish: true
    repositories:
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'

  - name: 'rcv-rhcdn-base-rhel-10'
    auto_publish: true
    repositories:
      - name: 'Red Hat Enterprise Linux 10 for x86_64 - BaseOS RPMs 10'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 10 for x86_64 - AppStream RPMs 10'
        product: 'Red Hat Enterprise Linux for x86_64'

...