---
# Settings related to Remote Execution
sat_settings_remote_execution:
  - name: 'remote_execution_ssh_user'
    value: 'remote-satellite'

  - name: 'remote_execution_ssh_port'
    value: 22

  - name: 'remote_execution_effective_user'
    value: 'root'

  - name: 'remote_execution_effective_user_method'
    value: 'sudo'
