---
# Define the Base and the Operating System level Host Groups
sat_base_host_groups:
  - name: 'hg-base'
    architecture: 'x86_64'
    organizations:
      - 'CRAZY.LAB'
    ansible_roles:
      - '{{ sat_scap_foreman_role_name }}'

sat_operating_system_host_groups:
  - name: 'hg-rhel-8'
    parent: 'hg-base'
    operatingsystem: 'RedHat 8.10'
    pxe_loader: 'PXELinux UEFI'
    ptable: 'Kickstart default'

  - name: 'hg-rhel-9'
    parent: 'hg-base'
    operatingsystem: 'RedHat 9.6'
    pxe_loader: 'PXELinux UEFI'
    ptable: 'Kickstart default'

  - name: 'hg-rhel-10'
    parent: 'hg-base'
    operatingsystem: 'RedHat 10.0'
    pxe_loader: 'PXELinux UEFI'
    ptable: 'Kickstart default'
