---
# Define the Service level Host Group
sat_service_host_groups:
  - name: 'hg-ansible_automation_platform-rhel-8'
    parent: 'hg-base/hg-rhel-8'
    root_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33626661366237376364393734323863333064663334343134323539323031333034303266393538
          3363613766353633303534646339613665353963396232650a323636643336643161343430653230
          61343864376538663130633864373834363864303166373936396162346333303766363732633165
          6236343463313665320a613735333131353763653766396266316665316462363834306561323136
          63326639656238386136663237353038613031393831383633633737326665613265

  - name: 'hg-default-rhel-8'
    parent: 'hg-base/hg-rhel-8'
    root_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36623464393630346164646437386336303662343839323730366330623438346338636530626566
          3263353266666133313561636261356631333961633232660a626137316230626637313335303534
          35633234663534666230313232323033353033383566303235656338643233333165623665623032
          3266643136323666660a656437373761373734373736316332393761653064393039316365646331
          39373232353635343832363732376535323339633938623063373439656133333863

  - name: 'hg-ansible_automation_platform-rhel-9'
    parent: 'hg-base/hg-rhel-9'
    root_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61346262663836613130346566303332633864646561326265656563616536343331316639663433
          6264316432626437303365613235326532336464383031310a653935636631313331303438343537
          31333031356638343639623665313830313838643565386230643163613737383461383934313432
          6232373538373133310a656431643135396435363237346239306137636135316164333366623133
          61663039643434373963333666343635386632303235303535336538653666306232

  - name: 'hg-default-rhel-9'
    parent: 'hg-base/hg-rhel-9'
    root_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61363661313764316631646366353931323066383934343865656335373233363164326439363062
          3830313264343262633539393331343531643366353933640a303332353965633132653339613837
          63363235343232623462356633613130616230303762326666343465303765653833313036326438
          6534373761386361620a323638343130336462303462393238623436623163653830313436326263
          32643665323831373533623931636361393563313561373863396461396437326662

  - name: 'hg-default-rhel-10'
    parent: 'hg-base/hg-rhel-10'
    root_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38393366383261646233316430366235353863343835633634643730636636363036633465646666
          6339363331336633346331363463393862386266333364300a646330313934666161613236363738
          30633638363435613637323636663139356634363133303565353933306436633964306539383763
          3834323066616635340a303537306639393739363132376566336538343736356537313064386139
          36323536313263343564636334386536316436346162313434393733343432343830