---
# Global Parameters for Remote Execution
sat_global_parameters_remote_execution:
  - name: 'p-remote_execution_ssh_keys'
    parameter_type: 'array'
    hidden_value: true
    value:
      - '{{ sat_remote_execution_ssh_public_key }}'
