
---
# Whether to enable the Foreman OpenSCAP Ansible role
sat_scap_enable_foreman_ansible_role: true

# Name of the Foreman OpenSCAP Ansible role
sat_scap_foreman_role_name: 'theforeman.foreman_scap_client'

# Whether to enable the OpenSCAP content that is shipped with Satellite
sat_scap_enable_default_content: true

# Path where to store the downloaded files of sat_scap_content_files
sat_scap_content_download_path: '/tmp'

# Whether to delete downloaded OpenSCAP files once imported
sat_scap_cleanup_temp_files: true

# OpenSCAP Compliance Policies
sat_scap_compliance_policies:
  - name: 'CIS-Server-L1-RHEL8-Policy'
    description: 'CIS Server Level 1 for RHEL 8'
    scap_content: 'Red Hat rhel8 default content'
    scap_content_profile: 'xccdf_org.ssgproject.content_profile_cis_server_l1'
    period: 'custom'
    cron_line: '0 1 * * *'
    deploy_by: 'ansible'
    organizations:
      - '{{ satellite_organization }}'
    locations:
      - '{{ satellite_location }}'
    hostgroups: []

  - name: 'CIS-Server-L2-RHEL8-Policy'
    description: 'CIS Server Level 2 for RHEL 8'
    scap_content: 'Red Hat rhel8 default content'
    scap_content_profile: 'xccdf_org.ssgproject.content_profile_cis'
    period: 'custom'
    cron_line: '0 1 * * *'
    deploy_by: 'ansible'
    organizations:
      - '{{ satellite_organization }}'
    locations:
      - '{{ satellite_location }}'
    hostgroups:
      - 'hg-base/hg-rhel-8'

  - name: 'CIS-Server-L1-RHEL9-Policy'
    description: 'CIS Server Level 1 for RHEL 9'
    scap_content: 'Red Hat rhel9 default content'
    scap_content_profile: 'xccdf_org.ssgproject.content_profile_cis_server_l1'
    period: 'custom'
    cron_line: '0 9 * * *'
    deploy_by: 'ansible'
    organizations:
      - '{{ satellite_organization }}'
    locations:
      - '{{ satellite_location }}'
    hostgroups: []

  - name: 'CIS-Server-L2-RHEL9-Policy'
    description: 'CIS Server Level 2 for RHEL 9'
    scap_content: 'Red Hat rhel9 default content'
    scap_content_profile: 'xccdf_org.ssgproject.content_profile_cis'
    period: 'custom'
    cron_line: '0 9 * * *'
    deploy_by: 'ansible'
    organizations:
      - '{{ satellite_organization }}'
    locations:
      - '{{ satellite_location }}'
    hostgroups:
      - 'hg-base/hg-rhel-9'

  - name: 'CIS-Server-L1-RHEL10-Policy'
    description: 'CIS Server Level 1 for RHEL 10'
    scap_content: 'Red Hat rhel10 default content'
    scap_content_profile: 'xccdf_org.ssgproject.content_profile_cis_server_l1'
    period: 'custom'
    cron_line: '0 17 * * *'
    deploy_by: 'ansible'
    organizations:
      - '{{ satellite_organization }}'
    locations:
      - '{{ satellite_location }}'
    hostgroups: []

  - name: 'CIS-Server-L2-RHEL10-Policy'
    description: 'CIS Server Level 2 for RHEL 10'
    scap_content: 'Red Hat rhel10 default content'
    scap_content_profile: 'xccdf_org.ssgproject.content_profile_cis'
    period: 'custom'
    cron_line: '0 17 * * *'
    deploy_by: 'ansible'
    organizations:
      - '{{ satellite_organization }}'
    locations:
      - '{{ satellite_location }}'
    hostgroups:
      - 'hg-base/hg-rhel-10'