---
# Variables used by the role redhat.rhel_system_roles.rhc
rhc_state: 'present'
rhc_auth:
  activation_keys:
    keys: ['{{ satellite_rhsm_activationkey }}']
  rhc_organization: '{{ satellite_rhsm_organization_id }}'

# Repositories to enable on the Capsule host
rhc_repositories:
  - name: 'rhel-9-for-x86_64-baseos-rpms'
    state: 'enabled'

  - name: 'rhel-9-for-x86_64-appstream-rpms'
    state: 'enabled'

  - name: 'satellite-capsule-6.17-for-rhel-9-x86_64-rpms'
    state: 'enabled'

  - name: 'satellite-maintenance-6.17-for-rhel-9-x86_64-rpms'
    state: 'enabled'

rhc_release: 9

rhc_insights:
  state: 'absent'
  autoupdate: false
  remediation: 'absent'
