---
# Firewalld rules for Satellite Capsule
# Managed by redhat.rhel_system_roles.firewall
# https://docs.redhat.com/en/documentation/red_hat_satellite/6.18/html/installing_capsule_server/preparing-environment-for-capsule-installation
firewall:
  - port:
      - '8000/tcp'
      - '8140/tcp'
      - '8443/tcp'
      - '9090/tcp'
      - '53/tcp'
      - '53/udp'
      - '67/udp'
      - '69/udp'
    service:
      - 'http'
      - 'https'
    zone: 'public'
    state: 'enabled'
    permanent: true
    immediate: true
